import type { MetadataRoute } from "next";

const BASE_URL = "https://imagepdf.tools";

export default function sitemap(): MetadataRoute.Sitemap {
    const lastModified = new Date();

    return [
        {
            url: BASE_URL,
            lastModified,
            changeFrequency: "weekly",
            priority: 1.0,
        },
        {
            url: `${BASE_URL}/compress-image`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.95,
        },
        {
            url: `${BASE_URL}/image-tools`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/pdf-tools`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/compress-png-online`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/convert-image-to-webp`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/reduce-image-size`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/compress-jpeg-online`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/convert-png-to-jpeg`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/merge-pdf`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.95,
        },
        {
            url: `${BASE_URL}/split-pdf`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.95,
        },
        {
            url: `${BASE_URL}/compress-pdf`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/jpg-to-png`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/webp-to-jpg`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/jpg-to-webp`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/png-to-webp`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/webp-to-png`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/convert/svg-to-png`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/convert/svg-to-jpg`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/convert/svg-to-webp`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/image-to-pdf`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${BASE_URL}/flip-image`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/rotate-image`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/crop-image`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/resize-image`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.85,
        },
        {
            url: `${BASE_URL}/remove-metadata`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.8,
        },
        {
            url: `${BASE_URL}/metadata-editor`,
            lastModified,
            changeFrequency: "weekly",
            priority: 0.8,
        },
        ...["png-to-jpeg", "jpeg-to-png", "png-to-webp", "jpeg-to-webp", "webp-to-jpeg", "webp-to-png", "svg-to-png", "svg-to-jpg", "svg-to-webp"].map((slug) => ({
            url: `${BASE_URL}/convert/${slug}`,
            lastModified,
            changeFrequency: "weekly" as const,
            priority: 0.85,
        })),
        {
            url: `${BASE_URL}/refund`,
            lastModified,
            changeFrequency: "monthly" as const,
            priority: 0.5,
        },
        {
            url: `${BASE_URL}/pricing`,
            lastModified,
            changeFrequency: "monthly",
            priority: 0.7,
        },
        {
            url: `${BASE_URL}/about`,
            lastModified,
            changeFrequency: "monthly",
            priority: 0.65,
        },
        {
            url: `${BASE_URL}/contact`,
            lastModified,
            changeFrequency: "yearly" as const,
            priority: 0.5,
        },
        {
            url: `${BASE_URL}/blog`,
            lastModified,
            changeFrequency: "weekly" as const,
            priority: 0.8,
        },
        ...[
            "online-file-converters-security-risk",
            "safely-compress-sensitive-pdf-documents",
            "what-is-image-metadata-exif-explained",
            "webp-vs-avif-image-format-seo-2026",
            "core-web-vitals-image-optimization",
            "ultimate-guide-pdf-compression-levels",
            "convert-jpg-to-pdf-without-losing-quality",
            "shrink-pdf-for-email-attachments",
            "batch-resize-images-social-media",
            "png-to-webp-why-website-owners-should-switch",
            "building-private-image-compressor-webassembly",
            "client-side-processing-saves-your-data",
            "choosing-right-image-format-compression-guide",
            "compress-image-to-exact-file-size",
            "compression-artifacts-field-guide",
            "how-browsers-handle-images",
            "image-compression-for-beginners",
            "image-compression-for-photographers",
            "image-optimization-ecommerce",
            "jpeg-quality-slider-explained",
            "lazy-loading-images-lcp-pitfall",
            "lossy-vs-lossless-compression",
            "trust-online-image-compression-tools",
            "progressive-jpegs-optimization",
            "responsive-images-guide",
            "shopify-image-optimization",
            "images-slowest-thing-on-your-website",
        ].map((slug) => ({
            url: `${BASE_URL}/blog/${slug}`,
            lastModified,
            changeFrequency: "monthly" as const,
            priority: 0.7,
        })),
    ];
}
